name: 'Ronex & Christian'
favicon: null
layout_spectrum: 0.40886809793300927
typography_spectrum: 0.09016369935125113
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.4053304756525904
  lightness: 0.42313543939962983
  saturation: 0.8984447901602834
  rhythmicContrast: 0.2664176016114652
purpose: []
